"""
Mood Mentor - Milestone 2
Task 4 - Confidence Score Validation
======================================================

Task 4 validates the confidence/probability outputs produced
by the TRUE multi-label Task 3 BERT model.

Checks performed:
    1. All 6 project emotions are returned.
    2. Every probability is between 0 and 1.
    3. Probabilities are dynamically generated by the model.
    4. Different inputs produce different predictions.
    5. The multi-label threshold is actually applied.
    6. Primary emotion is the highest-scoring emotion.

Usage:
    python verify_task4.py
        --model-dir .\multilabel_emotion_model
        --threshold 0.35
"""

import argparse

from emotion_labels import EMOTION_LABELS
from multi_label_classifier import (
    MultiLabelBERTClassifier,
    predict_multi_label,
    DEFAULT_THRESHOLD,
)


# ------------------------------------------------------------
# TEST SENTENCES
# ------------------------------------------------------------

CHECK_SENTENCES = [
    "I am excited about the new opportunity but nervous about the outcome.",
    "I just got some terrible news about a close friend.",
    "The presentation went so well, everyone applauded.",
    "I can't believe they cancelled the meeting without telling anyone.",
]


# ------------------------------------------------------------
# LOAD TASK 3 MULTI-LABEL MODEL
# ------------------------------------------------------------

def load_classifier(model_dir: str):
    """
    Load the TRUE multi-label BERT classifier created in Task 3.
    """
    print(f"Loading Task 3 multi-label model from '{model_dir}' ...")

    classifier = MultiLabelBERTClassifier.load(model_dir)

    print("Model loaded.\n")

    return classifier


# ------------------------------------------------------------
# MAIN
# ------------------------------------------------------------

def main():

    parser = argparse.ArgumentParser(
        description="Task 4 - confidence score validation"
    )

    parser.add_argument(
        "--model-dir",
        default="./multilabel_emotion_model",
        help="Path to the Task 3 multi-label model",
    )

    parser.add_argument(
        "--threshold",
        type=float,
        default=DEFAULT_THRESHOLD,
        help="Multi-label detection threshold",
    )

    args = parser.parse_args()

    # --------------------------------------------------------
    # LOAD MODEL
    # --------------------------------------------------------

    classifier = load_classifier(args.model_dir)

    print("=" * 65)
    print(" TASK 4 - CONFIDENCE SCORE VALIDATION")
    print("=" * 65)

    seen_confidence_signatures = set()

    all_checks_passed = True

    # --------------------------------------------------------
    # RUN TEST SENTENCES
    # --------------------------------------------------------

    for text in CHECK_SENTENCES:

        pred = predict_multi_label(
            classifier,
            text,
            threshold=args.threshold,
        )

        # ----------------------------------------------------
        # PRIMARY CONFIDENCE
        # ----------------------------------------------------

        primary_confidence = pred.all_scores[
            pred.primary_emotion
        ]

        # ----------------------------------------------------
        # CHECK 1:
        # ALL SIX EMOTIONS PRESENT
        # ----------------------------------------------------

        has_all_six = (
            set(pred.all_scores.keys())
            == set(EMOTION_LABELS)
        )

        # ----------------------------------------------------
        # CHECK 2:
        # ALL VALUES BETWEEN 0 AND 1
        # ----------------------------------------------------

        all_in_range = all(
            0.0 <= value <= 1.0
            for value in pred.all_scores.values()
        )

        # ----------------------------------------------------
        # CHECK 3:
        # PRIMARY EMOTION IS HIGHEST
        # ----------------------------------------------------

        highest_emotion = max(
            pred.all_scores,
            key=pred.all_scores.get,
        )

        primary_is_highest = (
            pred.primary_emotion == highest_emotion
        )

        # ----------------------------------------------------
        # CHECK 4:
        # DYNAMIC CONFIDENCE
        # ----------------------------------------------------

        looks_dynamic = (
            primary_confidence not in (0.0, 1.0)
            and len(str(round(primary_confidence, 4))) >= 4
        )

        # ----------------------------------------------------
        # TRACK OUTPUT SIGNATURE
        # ----------------------------------------------------

        signature = tuple(
            sorted(pred.all_scores.items())
        )

        seen_confidence_signatures.add(signature)

        # ----------------------------------------------------
        # OVERALL RESULT FOR THIS SENTENCE
        # ----------------------------------------------------

        ok = (
            has_all_six
            and all_in_range
            and primary_is_highest
            and looks_dynamic
        )

        all_checks_passed = (
            all_checks_passed and ok
        )

        # ----------------------------------------------------
        # DISPLAY
        # ----------------------------------------------------

        print(f"\nText: {text}")

        print(
            f"  Primary emotion   : "
            f"{pred.primary_emotion}"
        )

        print(
            f"  Confidence        : "
            f"{primary_confidence:.4f}"
        )

        print(
            f"  Detected "
            f"(>= {args.threshold}): "
            f"{', '.join(pred.detected_emotions)}"
        )

        print(
            f"  All 6 present     : "
            f"{'PASS' if has_all_six else 'FAIL'}"
        )

        print(
            f"  Valid range 0-1   : "
            f"{'PASS' if all_in_range else 'FAIL'}"
        )

        print(
            f"  Primary is highest : "
            f"{'PASS' if primary_is_highest else 'FAIL'}"
        )

        print(
            f"  Dynamic confidence : "
            f"{'PASS' if looks_dynamic else 'FAIL'}"
        )

        print("\n  Emotion probabilities:")

        for emotion, score in sorted(
            pred.all_scores.items(),
            key=lambda item: item[1],
            reverse=True,
        ):
            print(
                f"    {emotion:10s}: "
                f"{score:.4f}"
            )

    # --------------------------------------------------------
    # CHECK 5:
    # DIFFERENT INPUTS PRODUCE DIFFERENT OUTPUTS
    # --------------------------------------------------------

    print("\n" + "-" * 65)

    unique_check = (
        len(seen_confidence_signatures)
        == len(CHECK_SENTENCES)
    )

    print(
        "Distinct outputs per distinct input: "
        f"{'PASS' if unique_check else 'FAIL'}"
    )

    all_checks_passed = (
        all_checks_passed and unique_check
    )

    # --------------------------------------------------------
    # FINAL RESULT
    # --------------------------------------------------------

    print("=" * 65)

    if all_checks_passed:

        print(
            " TASK 4 OVERALL: ALL CHECKS PASSED"
        )

    else:

        print(
            " TASK 4 OVERALL: SOME CHECKS FAILED"
        )

        print(
            " Review the failed checks above."
        )

    print("=" * 65)


# ------------------------------------------------------------
# ENTRY POINT
# ------------------------------------------------------------

if __name__ == "__main__":
    main()